-- Common ICD-10 codes
INSERT INTO icd10_codes (code, description) VALUES
('E11.9',  'Type 2 diabetes mellitus without complications'),
('E11.65', 'Type 2 diabetes mellitus with hyperglycemia'),
('E78.5',  'Dyslipidemia, unspecified'),
('E03.9',  'Hypothyroidism, unspecified'),
('E66.01', 'Morbid obesity due to excess calories'),
('I10',    'Essential (primary) hypertension'),
('I25.10', 'Atherosclerotic heart disease of native coronary artery'),
('I48.91', 'Unspecified atrial fibrillation'),
('I50.9',  'Heart failure, unspecified'),
('I63.9',  'Cerebral infarction, unspecified'),
('J06.9',  'Acute upper respiratory infection, unspecified'),
('J18.9',  'Pneumonia, unspecified organism'),
('J20.9',  'Acute bronchitis, unspecified'),
('J30.1',  'Allergic rhinitis due to pollen'),
('J44.1',  'Chronic obstructive pulmonary disease with acute exacerbation'),
('J45.20', 'Mild intermittent asthma, uncomplicated'),
('J45.50', 'Severe persistent asthma, uncomplicated'),
('K21.0',  'Gastro-esophageal reflux disease with esophagitis'),
('K58.9',  'Irritable bowel syndrome without diarrhea'),
('K76.0',  'Fatty liver, not elsewhere classified'),
('M54.5',  'Low back pain'),
('M54.2',  'Cervicalgia'),
('M79.3',  'Panniculitis, unspecified'),
('M17.11', 'Primary osteoarthritis, right knee'),
('M17.12', 'Primary osteoarthritis, left knee'),
('G43.909','Migraine, unspecified, not intractable'),
('G47.00', 'Insomnia, unspecified'),
('G89.29', 'Other chronic pain'),
('F32.1',  'Major depressive disorder, single episode, moderate'),
('F32.9',  'Major depressive disorder, single episode, unspecified'),
('F41.1',  'Generalized anxiety disorder'),
('F41.9',  'Anxiety disorder, unspecified'),
('F17.210','Nicotine dependence, cigarettes, uncomplicated'),
('F10.20', 'Alcohol dependence, uncomplicated'),
('N39.0',  'Urinary tract infection, site not specified'),
('N18.3',  'Chronic kidney disease, stage 3'),
('R05.9',  'Cough, unspecified'),
('R10.9',  'Unspecified abdominal pain'),
('R51.9',  'Headache, unspecified'),
('R53.83', 'Other fatigue'),
('R73.03', 'Prediabetes'),
('L30.9',  'Dermatitis, unspecified'),
('L70.0',  'Acne vulgaris'),
('B34.9',  'Viral infection, unspecified'),
('Z00.00', 'Encounter for general adult medical exam without abnormal findings'),
('Z00.01', 'Encounter for general adult medical exam with abnormal findings'),
('Z12.31', 'Encounter for screening mammogram for malignant neoplasm of breast'),
('Z23',    'Encounter for immunization'),
('Z71.3',  'Dietary counseling and surveillance'),
('Z79.4',  'Long term (current) use of insulin'),
('Z87.891','Personal history of nicotine dependence'),
('D64.9',  'Anemia, unspecified'),
('B00.9',  'Herpesviral infection, unspecified'),
('H66.90', 'Otitis media, unspecified, unspecified ear'),
('J02.9',  'Acute pharyngitis, unspecified'),
('R50.9',  'Fever, unspecified'),
('R11.2',  'Nausea with vomiting, unspecified'),
('M25.511','Pain in right shoulder'),
('M25.512','Pain in left shoulder'),
('R42',    'Dizziness and giddiness'),
('S93.401A','Sprain of unspecified ligament of right ankle, initial encounter'),
('T78.40XA','Allergy, unspecified, initial encounter'),
('Z96.641','Presence of right artificial hip joint'),
('Z96.642','Presence of left artificial hip joint'),
('G20',    'Parkinson disease'),
('E55.9',  'Vitamin D deficiency, unspecified'),
('B95.61', 'MRSA infection as the cause of diseases classified elsewhere'),
('K35.80', 'Unspecified acute appendicitis'),
('N40.0',  'Benign prostatic hyperplasia without lower urinary tract symptoms');

-- Common CPT codes
INSERT INTO cpt_codes (code, description) VALUES
('99201', 'Office visit, new patient, minimal'),
('99202', 'Office visit, new patient, low complexity'),
('99203', 'Office visit, new patient, moderate complexity'),
('99204', 'Office visit, new patient, high complexity'),
('99205', 'Office visit, new patient, comprehensive'),
('99211', 'Office visit, established patient, minimal'),
('99212', 'Office visit, established patient, low complexity'),
('99213', 'Office visit, established patient, moderate complexity'),
('99214', 'Office visit, established patient, high complexity'),
('99215', 'Office visit, established patient, comprehensive'),
('99381', 'Preventive visit, new patient, infant'),
('99391', 'Preventive visit, established patient, infant'),
('99385', 'Preventive visit, new patient, 18-39 years'),
('99386', 'Preventive visit, new patient, 40-64 years'),
('99395', 'Preventive visit, established patient, 18-39 years'),
('99396', 'Preventive visit, established patient, 40-64 years'),
('99397', 'Preventive visit, established patient, 65+ years'),
('99281', 'Emergency department visit, minimal'),
('99282', 'Emergency department visit, low complexity'),
('99283', 'Emergency department visit, moderate complexity'),
('99284', 'Emergency department visit, high complexity'),
('99285', 'Emergency department visit, comprehensive'),
('90471', 'Immunization administration, first vaccine'),
('90472', 'Immunization administration, each additional vaccine'),
('90658', 'Influenza vaccine, trivalent'),
('90662', 'Influenza vaccine, quadrivalent'),
('36415', 'Venipuncture for blood draw'),
('80053', 'Comprehensive metabolic panel'),
('80061', 'Lipid panel'),
('85025', 'Complete blood count with differential'),
('81001', 'Urinalysis, automated with microscopy'),
('71046', 'Chest X-ray, 2 views'),
('71260', 'CT chest with contrast'),
('73030', 'Shoulder X-ray, minimum 2 views'),
('73560', 'Knee X-ray, 1 or 2 views'),
('73610', 'Ankle X-ray, minimum 3 views'),
('93000', 'Electrocardiogram, routine, 12-lead'),
('93306', 'Echocardiography, transthoracic, complete'),
('10060', 'Incision and drainage of abscess, simple'),
('11102', 'Tangential biopsy of skin, single lesion'),
('17000', 'Destruction of premalignant lesion, first lesion'),
('29125', 'Short arm splint application'),
('97110', 'Therapeutic exercises, each 15 minutes'),
('97140', 'Manual therapy techniques, each 15 minutes'),
('96372', 'Therapeutic injection, subcutaneous or intramuscular'),
('99441', 'Telephone E/M, 5-10 minutes'),
('99442', 'Telephone E/M, 11-20 minutes'),
('99443', 'Telephone E/M, 21-30 minutes'),
('99421', 'Online digital E/M, 5-10 minutes'),
('G0108', 'Diabetes self-management training, individual'),
('G0438', 'Annual wellness visit, initial');

-- Sample encounters for existing patients
INSERT INTO encounters (patient_id, encounter_date, encounter_type, status, provider, reason) VALUES
(1, '2025-09-15', 'OFFICE_VISIT',  'COMPLETED', 'Dr. Roberts', 'Seasonal allergy symptoms - congestion, sneezing'),
(1, '2025-10-13', 'OFFICE_VISIT',  'COMPLETED', 'Dr. Roberts', 'Allergy follow-up visit'),
(2, '2025-08-20', 'ANNUAL_EXAM',   'COMPLETED', 'Dr. Thompson', 'Annual physical examination'),
(3, '2025-11-05', 'OFFICE_VISIT',  'COMPLETED', 'Dr. Garcia', 'Persistent lower back pain for 2 weeks'),
(4, '2025-12-10', 'OFFICE_VISIT',  'COMPLETED', 'Dr. Kim', 'Routine diabetes management'),
(5, '2026-01-08', 'NEW_PATIENT',   'COMPLETED', 'Dr. Roberts', 'New patient intake and baseline evaluation'),
(1, '2026-03-15', 'OFFICE_VISIT',  'PLANNED',   'Dr. Roberts', 'Spring allergy season check-in'),
(4, '2026-03-10', 'OFFICE_VISIT',  'PLANNED',   'Dr. Kim', 'Diabetes 3-month follow-up');

-- Link existing notes to encounters
UPDATE notes SET encounter_id = 1 WHERE patient_id = 1 AND content LIKE '%seasonal allergies%';
UPDATE notes SET encounter_id = 2 WHERE patient_id = 1 AND content LIKE '%Follow-up visit%';
UPDATE notes SET encounter_id = 3 WHERE patient_id = 2 AND content LIKE '%Annual physical%';
UPDATE notes SET encounter_id = 4 WHERE patient_id = 3 AND content LIKE '%lower back pain%';
UPDATE notes SET encounter_id = 5 WHERE patient_id = 4 AND content LIKE '%diabetes management%';
UPDATE notes SET encounter_id = 6 WHERE patient_id = 5 AND content LIKE '%New patient intake%';

-- Assign diagnoses to encounters
INSERT INTO encounter_diagnoses (encounter_id, icd10_code_id) VALUES
(1, (SELECT id FROM icd10_codes WHERE code = 'J30.1')),
(2, (SELECT id FROM icd10_codes WHERE code = 'J30.1')),
(3, (SELECT id FROM icd10_codes WHERE code = 'Z00.00')),
(3, (SELECT id FROM icd10_codes WHERE code = 'I10')),
(4, (SELECT id FROM icd10_codes WHERE code = 'M54.5')),
(5, (SELECT id FROM icd10_codes WHERE code = 'E11.9')),
(6, (SELECT id FROM icd10_codes WHERE code = 'Z00.00'));

-- Assign procedures to encounters
INSERT INTO encounter_procedures (encounter_id, cpt_code_id) VALUES
(1, (SELECT id FROM cpt_codes WHERE code = '99213')),
(2, (SELECT id FROM cpt_codes WHERE code = '99212')),
(3, (SELECT id FROM cpt_codes WHERE code = '99396')),
(3, (SELECT id FROM cpt_codes WHERE code = '80053')),
(3, (SELECT id FROM cpt_codes WHERE code = '85025')),
(3, (SELECT id FROM cpt_codes WHERE code = '80061')),
(4, (SELECT id FROM cpt_codes WHERE code = '99214')),
(5, (SELECT id FROM cpt_codes WHERE code = '99214')),
(5, (SELECT id FROM cpt_codes WHERE code = '80053')),
(6, (SELECT id FROM cpt_codes WHERE code = '99205')),
(6, (SELECT id FROM cpt_codes WHERE code = '36415')),
(6, (SELECT id FROM cpt_codes WHERE code = '85025'));
